version: 2
updates:
  - package-ecosystem: "npm" # Specify the package ecosystem (e.g., npm, pip, etc.)
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" # Set the update schedule interval
