// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_webhook_eventId_ from "./routes/api/webhook/[eventId].ts";
import * as $api_webhook_index from "./routes/api/webhook/index.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $EventList from "./islands/EventList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/webhook/[eventId].ts": $api_webhook_eventId_,
    "./routes/api/webhook/index.ts": $api_webhook_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/EventList.tsx": $EventList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
